import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Buscar empresa "Vertice teste" (ambiente de testes)
  const company = await prisma.company.findFirst({
    where: { name: { contains: 'teste', mode: 'insensitive' } },
  })
  if (!company) {
    console.error('Empresa de teste não encontrada. Verifique o nome no banco.')
    return
  }
  const companyId = company.id
  console.log(`\nInserindo dados para empresa: ${company.name} (${companyId})\n`)

  const year = new Date().getFullYear()
  let seq = 0
  const genCode = () => `DEP-${year}-${String(++seq).padStart(3, '0')}`

  // ════════════════════════════════════════════
  // 20 MATERIAIS
  // ════════════════════════════════════════════
  const materiais = [
    {
      code: genCode(),
      name: 'Cimento CP II 50kg',
      description: 'Cimento Portland Composto CP II-E-32, saco 50kg',
      category: 'Cimento e Argamassa',
      unit: 'saco',
      brand: 'Votorantim',
      minQuantity: 20,
      quantity: 85,
      averageCost: 35.50,
      locationShelf: '1', locationSection: 'A', locationDetail: 'Prateleira inferior',
    },
    {
      code: genCode(),
      name: 'Areia média lavada',
      description: 'Areia média lavada para construção civil',
      category: 'Cimento e Argamassa',
      unit: 'm³',
      brand: 'Mineração Central',
      minQuantity: 5,
      quantity: 22,
      averageCost: 120.00,
      locationShelf: '1', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Brita 1',
      description: 'Brita graduada simples, 9,5 a 19mm',
      category: 'Cimento e Argamassa',
      unit: 'm³',
      brand: 'Pedreira São Paulo',
      minQuantity: 5,
      quantity: 18,
      averageCost: 110.00,
      locationShelf: '1', locationSection: 'C',
    },
    {
      code: genCode(),
      name: 'Tijolo cerâmico 9 furos',
      description: 'Tijolo cerâmico 9 furos 9x14x19cm',
      category: 'Alvenaria',
      unit: 'un',
      brand: 'Cerâmica Boa Vista',
      minQuantity: 500,
      quantity: 3200,
      averageCost: 0.95,
      locationShelf: '2', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Vergalhão CA-50 10mm',
      description: 'Vergalhão de aço CA-50 diâmetro 10mm, barra 12m',
      category: 'Aço e Ferragem',
      unit: 'un',
      brand: 'Gerdau',
      minQuantity: 50,
      quantity: 180,
      averageCost: 45.80,
      locationShelf: '2', locationSection: 'B', locationDetail: 'Gaiola de ferro',
    },
    {
      code: genCode(),
      name: 'Vergalhão CA-60 8mm',
      description: 'Vergalhão de aço CA-60 diâmetro 8mm, barra 12m',
      category: 'Aço e Ferragem',
      unit: 'un',
      brand: 'Gerdau',
      minQuantity: 30,
      quantity: 95,
      averageCost: 28.40,
      locationShelf: '2', locationSection: 'C',
    },
    {
      code: genCode(),
      name: 'Tubo PVC esgoto 100mm',
      description: 'Tubo PVC série normal esgoto predial DN100, 6m',
      category: 'Hidráulica',
      unit: 'un',
      brand: 'Tigre',
      minQuantity: 10,
      quantity: 42,
      averageCost: 68.90,
      locationShelf: '3', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Tubo PVC água fria 25mm',
      description: 'Tubo PVC rígido água fria 25mm PN 60, 6m',
      category: 'Hidráulica',
      unit: 'un',
      brand: 'Amanco',
      minQuantity: 10,
      quantity: 35,
      averageCost: 32.50,
      locationShelf: '3', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Cabo elétrico flexível 2,5mm²',
      description: 'Cabo elétrico flexível 750V 2,5mm², rolo 100m',
      category: 'Elétrica',
      unit: 'rolo',
      brand: 'Ficap',
      minQuantity: 5,
      quantity: 18,
      averageCost: 185.00,
      locationShelf: '3', locationSection: 'C', locationDetail: 'Armário elétrico',
    },
    {
      code: genCode(),
      name: 'Cabo elétrico flexível 4mm²',
      description: 'Cabo elétrico flexível 750V 4mm², rolo 100m',
      category: 'Elétrica',
      unit: 'rolo',
      brand: 'Ficap',
      minQuantity: 3,
      quantity: 8,
      averageCost: 285.00,
      locationShelf: '3', locationSection: 'D',
    },
    {
      code: genCode(),
      name: 'Disjuntor monopolar 20A',
      description: 'Disjuntor monopolar termomagnético 20A, curva C',
      category: 'Elétrica',
      unit: 'un',
      brand: 'Schneider Electric',
      minQuantity: 10,
      quantity: 38,
      averageCost: 22.50,
      locationShelf: '4', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Tinta acrílica branca 18L',
      description: 'Tinta acrílica premium acabamento fosco, lata 18L',
      category: 'Tintas e Solventes',
      unit: 'un',
      brand: 'Suvinil',
      minQuantity: 5,
      quantity: 14,
      averageCost: 185.00,
      locationShelf: '4', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Massa corrida PVA 25kg',
      description: 'Massa corrida PVA para interiores, balde 25kg',
      category: 'Tintas e Solventes',
      unit: 'un',
      brand: 'Coral',
      minQuantity: 5,
      quantity: 20,
      averageCost: 68.00,
      locationShelf: '4', locationSection: 'C',
    },
    {
      code: genCode(),
      name: 'Piso cerâmico 45x45cm',
      description: 'Piso cerâmico esmaltado 45x45cm ref. STONE BEGE',
      category: 'Revestimento e Acabamento',
      unit: 'm²',
      brand: 'Portobello',
      minQuantity: 20,
      quantity: 124,
      averageCost: 42.90,
      locationShelf: '5', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Rejunte cinza 1kg',
      description: 'Rejunte epóxi cinza platina, embalagem 1kg',
      category: 'Revestimento e Acabamento',
      unit: 'un',
      brand: 'Quartzolit',
      minQuantity: 10,
      quantity: 45,
      averageCost: 28.90,
      locationShelf: '5', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Argamassa AC-II 20kg',
      description: 'Argamassa colante tipo AC-II para porcelanato, saco 20kg',
      category: 'Cimento e Argamassa',
      unit: 'saco',
      brand: 'Votomassa',
      minQuantity: 20,
      quantity: 76,
      averageCost: 32.00,
      locationShelf: '5', locationSection: 'C',
    },
    {
      code: genCode(),
      name: 'Impermeabilizante manta 1mm',
      description: 'Manta asfáltica impermeabilizante alumínio 1mm, rolo 10m²',
      category: 'Impermeabilização',
      unit: 'rolo',
      brand: 'Vedacit',
      minQuantity: 5,
      quantity: 12,
      averageCost: 145.00,
      locationShelf: '6', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Gesso em pó 20kg',
      description: 'Gesso para construção, saco 20kg',
      category: 'Revestimento e Acabamento',
      unit: 'saco',
      brand: 'Infibra',
      minQuantity: 10,
      quantity: 33,
      averageCost: 22.00,
      locationShelf: '6', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Parafuso Phillips 4,2x38mm',
      description: 'Parafuso zincado Phillips cabeça chata 4,2x38mm, caixa 500un',
      category: 'Fixação',
      unit: 'cx',
      brand: 'Ciser',
      minQuantity: 5,
      quantity: 18,
      averageCost: 45.00,
      locationShelf: '7', locationSection: 'A', locationDetail: 'Painel de parafusos',
    },
    {
      code: genCode(),
      name: 'Fio de nylon 2,4mm p/ roçadeira',
      description: 'Fio de nylon redondo 2,4mm para roçadeira, rolo 100m',
      category: 'Outros',
      unit: 'rolo',
      brand: 'Oregon',
      minQuantity: 3,
      quantity: 7,
      averageCost: 38.90,
      locationShelf: '7', locationSection: 'B',
    },
  ]

  // ════════════════════════════════════════════
  // 10 FERRAMENTAS
  // ════════════════════════════════════════════
  const ferramentas = [
    {
      code: genCode(),
      name: 'Furadeira de impacto 3/4"',
      category: 'Perfuração',
      unit: 'un',
      brand: 'Bosch',
      model: 'GSB 21-2 RE',
      serialNumber: 'SN-GSB-2024-001',
      toolType: 'ELECTRIC',
      voltage: '220V',
      power: '1100 W',
      purchaseDate: new Date('2024-01-15'),
      warrantyMonthsTool: 12,
      warrantyExpiry: new Date('2025-01-15'),
      isUnderWarranty: false,
      authorizedName: 'Bosch Service Center',
      authorizedPhone: '(11) 3456-7890',
      authorizedCity: 'São Paulo/SP',
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 890.00,
      locationShelf: '8', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Esmerilhadeira angular 7"',
      category: 'Corte e Desbaste',
      unit: 'un',
      brand: 'Makita',
      model: 'GA7020',
      serialNumber: 'SN-GA7-2024-002',
      toolType: 'ELECTRIC',
      voltage: '220V',
      power: '2200 W',
      purchaseDate: new Date('2024-02-10'),
      warrantyMonthsTool: 12,
      warrantyExpiry: new Date('2025-02-10'),
      isUnderWarranty: false,
      authorizedName: 'Makita Service',
      authorizedPhone: '(11) 4567-8901',
      authorizedCity: 'São Paulo/SP',
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 1250.00,
      locationShelf: '8', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Serra circular 7-1/4"',
      category: 'Corte e Desbaste',
      unit: 'un',
      brand: 'DeWalt',
      model: 'DWE575',
      serialNumber: 'SN-DWE-2024-003',
      toolType: 'ELECTRIC',
      voltage: 'BIVOLT',
      power: '1600 W',
      purchaseDate: new Date('2024-03-05'),
      warrantyMonthsTool: 12,
      warrantyExpiry: new Date('2025-03-05'),
      isUnderWarranty: false,
      authorizedName: 'DeWalt Service',
      authorizedPhone: '(11) 2345-6789',
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 980.00,
      locationShelf: '8', locationSection: 'C',
    },
    {
      code: genCode(),
      name: 'Parafusadeira/Furadeira 18V',
      category: 'Perfuração',
      unit: 'un',
      brand: 'Bosch',
      model: 'GSR 18V-50',
      serialNumber: 'SN-GSR-2024-004',
      toolType: 'ELECTRIC',
      voltage: 'BATTERY',
      power: '18 V',
      purchaseDate: new Date('2024-04-20'),
      warrantyMonthsTool: 24,
      warrantyExpiry: new Date('2026-04-20'),
      isUnderWarranty: true,
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 780.00,
      locationShelf: '8', locationSection: 'D',
    },
    {
      code: genCode(),
      name: 'Betoneira 400L',
      category: 'Mistura e Concretagem',
      unit: 'un',
      brand: 'CSM',
      model: 'B400R',
      serialNumber: 'SN-B400-2023-005',
      toolType: 'ELECTRIC',
      voltage: '220V',
      power: '2 CV',
      purchaseDate: new Date('2023-06-10'),
      warrantyMonthsTool: 12,
      warrantyExpiry: new Date('2024-06-10'),
      isUnderWarranty: false,
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 3200.00,
      locationShelf: '9', locationSection: 'A', locationDetail: 'Área externa',
    },
    {
      code: genCode(),
      name: 'Vibrador de concreto 38mm',
      category: 'Mistura e Concretagem',
      unit: 'un',
      brand: 'Wacker Neuson',
      model: 'M2000',
      serialNumber: 'SN-WN-2024-006',
      toolType: 'ELECTRIC',
      voltage: '220V',
      power: '1500 W',
      purchaseDate: new Date('2024-01-30'),
      warrantyMonthsTool: 12,
      warrantyExpiry: new Date('2025-01-30'),
      isUnderWarranty: false,
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 1850.00,
      locationShelf: '9', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Nível a laser autonivelante',
      category: 'Medição e Topografia',
      unit: 'un',
      brand: 'Leica',
      model: 'LINO L2G',
      serialNumber: 'SN-LL2G-2024-007',
      toolType: 'MEASURING',
      voltage: 'BATTERY',
      power: '4xAA',
      purchaseDate: new Date('2024-05-12'),
      warrantyMonthsTool: 24,
      warrantyExpiry: new Date('2026-05-12'),
      isUnderWarranty: true,
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 2400.00,
      locationShelf: '9', locationSection: 'C', locationDetail: 'Maleta protetora',
    },
    {
      code: genCode(),
      name: 'Martelete demolidor SDS-Plus',
      category: 'Demolição',
      unit: 'un',
      brand: 'Makita',
      model: 'HR2470',
      serialNumber: 'SN-HR24-2023-008',
      toolType: 'ELECTRIC',
      voltage: '220V',
      power: '780 W',
      purchaseDate: new Date('2023-08-22'),
      warrantyMonthsTool: 12,
      warrantyExpiry: new Date('2024-08-22'),
      isUnderWarranty: false,
      lastMaintenance: new Date('2025-01-10'),
      nextMaintenance: new Date('2025-07-10'),
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 1100.00,
      locationShelf: '9', locationSection: 'D',
    },
    {
      code: genCode(),
      name: 'Trena a laser 50m',
      category: 'Medição e Topografia',
      unit: 'un',
      brand: 'Bosch',
      model: 'GLM 50 C',
      serialNumber: 'SN-GLM-2024-009',
      toolType: 'MEASURING',
      voltage: 'BATTERY',
      power: '2xAAA',
      purchaseDate: new Date('2024-03-18'),
      warrantyMonthsTool: 12,
      warrantyExpiry: new Date('2025-03-18'),
      isUnderWarranty: false,
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 520.00,
      locationShelf: '10', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Compactador de solo',
      category: 'Compactação',
      unit: 'un',
      brand: 'Wacker Neuson',
      model: 'BS50-2',
      serialNumber: 'SN-BS50-2022-010',
      toolType: 'MANUAL',
      purchaseDate: new Date('2022-11-05'),
      warrantyMonthsTool: 12,
      warrantyExpiry: new Date('2023-11-05'),
      isUnderWarranty: false,
      lastMaintenance: new Date('2024-11-05'),
      nextMaintenance: new Date('2025-11-05'),
      requiresCustody: true,
      isConsumable: false,
      minQuantity: 1,
      quantity: 1,
      averageCost: 4800.00,
      locationShelf: '10', locationSection: 'B', locationDetail: 'Área externa coberta',
    },
  ]

  // ════════════════════════════════════════════
  // 10 EPIs
  // ════════════════════════════════════════════
  const epis = [
    {
      code: genCode(),
      name: 'Capacete de segurança classe B',
      description: 'Capacete aba frontal classe B, CA 31469, cor branco',
      category: 'EPI - Cabeça',
      unit: 'un',
      brand: 'MSA',
      model: 'V-Gard',
      isEpi: true,
      minQuantity: 10,
      quantity: 35,
      averageCost: 48.90,
      locationShelf: '11', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Óculos de proteção ampla visão',
      description: 'Óculos proteção ampla visão incolor CA 10346',
      category: 'EPI - Olhos',
      unit: 'un',
      brand: '3M',
      model: 'SecureFit SF400',
      isEpi: true,
      minQuantity: 15,
      quantity: 52,
      averageCost: 18.50,
      locationShelf: '11', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Protetor auricular tipo plug',
      description: 'Protetor auricular plug espuma PU, CA 5674, NRR 26dB',
      category: 'EPI - Auditivo',
      unit: 'par',
      brand: 'Moldex',
      model: 'Spark Plugs',
      isEpi: true,
      minQuantity: 50,
      quantity: 180,
      averageCost: 2.80,
      locationShelf: '11', locationSection: 'C',
    },
    {
      code: genCode(),
      name: 'Luva de raspa cano médio',
      description: 'Luva raspa cano médio 23cm, CA 6484, tamanho único',
      category: 'EPI - Mãos',
      unit: 'par',
      brand: 'Volk',
      model: 'VL-100',
      isEpi: true,
      minQuantity: 20,
      quantity: 68,
      averageCost: 12.90,
      locationShelf: '11', locationSection: 'D',
    },
    {
      code: genCode(),
      name: 'Bota de segurança PVC preta',
      description: 'Bota PVC cano curto impermeável biqueira aço CA 14045',
      category: 'EPI - Pés',
      unit: 'par',
      brand: 'Vulcabras',
      model: 'Works Boot',
      isEpi: true,
      minQuantity: 5,
      quantity: 22,
      averageCost: 89.00,
      locationShelf: '12', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Cinto de segurança tipo paraquedista',
      description: 'Cinto paraquedista 5 pontos NR-35, CA 35987, completo',
      category: 'EPI - Altura',
      unit: 'un',
      brand: 'Petzl',
      model: 'VERTEX VENT',
      isEpi: true,
      minQuantity: 5,
      quantity: 12,
      averageCost: 385.00,
      locationShelf: '12', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Máscara semifacial PFF2',
      description: 'Máscara respirador semifacial PFF2 sem válvula CA 4469',
      category: 'EPI - Respiratório',
      unit: 'un',
      brand: '3M',
      model: '8822',
      isEpi: true,
      minQuantity: 20,
      quantity: 95,
      averageCost: 8.50,
      locationShelf: '12', locationSection: 'C',
    },
    {
      code: genCode(),
      name: 'Colete refletivo laranja',
      description: 'Colete refletivo classe 2 laranja faixas prata CA 38690',
      category: 'EPI - Tronco',
      unit: 'un',
      brand: 'Carbografite',
      isEpi: true,
      minQuantity: 10,
      quantity: 30,
      averageCost: 32.00,
      locationShelf: '12', locationSection: 'D',
    },
    {
      code: genCode(),
      name: 'Óculos para solda escuridão 5',
      description: 'Óculos solda oxiacetilênica escuridão 5, CA 10346',
      category: 'EPI - Olhos',
      unit: 'un',
      brand: 'Danny',
      isEpi: true,
      minQuantity: 3,
      quantity: 8,
      averageCost: 24.50,
      locationShelf: '13', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Talabarte de segurança duplo',
      description: 'Talabarte duplo com absorvedor de energia CA 29734',
      category: 'EPI - Altura',
      unit: 'un',
      brand: 'Petzl',
      model: 'ABSORBICA-Y',
      isEpi: true,
      minQuantity: 3,
      quantity: 8,
      averageCost: 420.00,
      locationShelf: '13', locationSection: 'B',
    },
  ]

  // ════════════════════════════════════════════
  // 10 UNIFORMES
  // ════════════════════════════════════════════
  const uniformes = [
    {
      code: genCode(),
      name: 'Camiseta manga longa dry fit',
      description: 'Camiseta operacional manga longa dry fit laranja c/ logo',
      category: 'Uniformes',
      unit: 'un',
      brand: 'Uniformes Brasil',
      isUniform: true,
      minQuantity: 5,
      quantity: 45,
      averageCost: 68.00,
      locationShelf: '14', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Calça cargo operacional',
      description: 'Calça cargo brim 100% algodão reforçada cor chumbo',
      category: 'Uniformes',
      unit: 'un',
      brand: 'Worker',
      isUniform: true,
      minQuantity: 5,
      quantity: 38,
      averageCost: 95.00,
      locationShelf: '14', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Boné aba reta bordado',
      description: 'Boné aba reta 100% algodão bordado logo empresa',
      category: 'Uniformes',
      unit: 'un',
      brand: 'Uniformes Brasil',
      isUniform: true,
      minQuantity: 5,
      quantity: 28,
      averageCost: 28.00,
      locationShelf: '14', locationSection: 'C',
    },
    {
      code: genCode(),
      name: 'Jaqueta corta-vento',
      description: 'Jaqueta corta-vento nylon impermeável com capuz logo bordado',
      category: 'Uniformes',
      unit: 'un',
      brand: 'Worker',
      isUniform: true,
      minQuantity: 3,
      quantity: 15,
      averageCost: 145.00,
      locationShelf: '14', locationSection: 'D',
    },
    {
      code: genCode(),
      name: 'Bota de couro amarela s/ biqueira',
      description: 'Bota couro cano curto amarela sem biqueira NR-18',
      category: 'Uniformes',
      unit: 'par',
      brand: 'Bracol',
      isUniform: true,
      minQuantity: 5,
      quantity: 20,
      averageCost: 125.00,
      locationShelf: '15', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Camisa polo bordada',
      description: 'Camisa polo piquet bordado logo empresa cor laranja',
      category: 'Uniformes',
      unit: 'un',
      brand: 'Uniformes Brasil',
      isUniform: true,
      minQuantity: 5,
      quantity: 32,
      averageCost: 72.00,
      locationShelf: '15', locationSection: 'B',
    },
    {
      code: genCode(),
      name: 'Bermuda brim operacional',
      description: 'Bermuda brim reforçada operacional cor cinza',
      category: 'Uniformes',
      unit: 'un',
      brand: 'Worker',
      isUniform: true,
      minQuantity: 3,
      quantity: 18,
      averageCost: 65.00,
      locationShelf: '15', locationSection: 'C',
    },
    {
      code: genCode(),
      name: 'Colete multibolsos',
      description: 'Colete repórter multibolsos brim logo bordado',
      category: 'Uniformes',
      unit: 'un',
      brand: 'Uniformes Brasil',
      isUniform: true,
      minQuantity: 3,
      quantity: 12,
      averageCost: 88.00,
      locationShelf: '15', locationSection: 'D',
    },
    {
      code: genCode(),
      name: 'Meia cano médio (par)',
      description: 'Meia trabalho cano médio antiderrapante algodão 70%',
      category: 'Uniformes',
      unit: 'par',
      brand: 'Lupo',
      isUniform: true,
      minQuantity: 10,
      quantity: 48,
      averageCost: 18.00,
      locationShelf: '16', locationSection: 'A',
    },
    {
      code: genCode(),
      name: 'Touca ninja balaclava',
      description: 'Touca ninja proteção solar UV50+ cor preta',
      category: 'Uniformes',
      unit: 'un',
      brand: 'Carbografite',
      isUniform: true,
      minQuantity: 5,
      quantity: 25,
      averageCost: 22.00,
      locationShelf: '16', locationSection: 'B',
    },
  ]

  // ════════════════════════════════════════════
  // INSERIR TODOS NO BANCO
  // ════════════════════════════════════════════
  const allItems = [...materiais, ...ferramentas, ...epis, ...uniformes]
  let created = 0
  let skipped = 0

  for (const item of allItems) {
    // Verificar se já existe pelo código
    const exists = await (prisma as any).stockItem.findFirst({
      where: { companyId, code: item.code },
    })
    if (exists) {
      console.log(`⏭  Já existe: ${item.code} — ${item.name}`)
      skipped++
      continue
    }

    const lf = (item as any)
    const locationFull = [
      lf.locationShelf   ? `Estante ${lf.locationShelf}`   : null,
      lf.locationSection ? `Seção ${lf.locationSection}`    : null,
      lf.locationDetail  ?? null,
    ].filter(Boolean).join(' / ')

    await (prisma as any).stockItem.create({
      data: {
        companyId,
        code:             item.code,
        name:             item.name,
        description:      (item as any).description    ?? null,
        category:         (item as any).category       ?? null,
        unit:             item.unit,
        brand:            (item as any).brand          ?? null,
        model:            (item as any).model          ?? null,
        serialNumber:     (item as any).serialNumber   ?? null,
        quantity:         item.quantity,
        minQuantity:      item.minQuantity,
        averageCost:      item.averageCost,
        locationShelf:    (item as any).locationShelf   ?? null,
        locationSection:  (item as any).locationSection ?? null,
        locationDetail:   (item as any).locationDetail  ?? null,
        locationFull:     locationFull || null,
        isConsumable:     (item as any).isConsumable    ?? true,
        requiresCustody:  (item as any).requiresCustody ?? false,
        isEpi:            (item as any).isEpi           ?? false,
        isUniform:        (item as any).isUniform       ?? false,
        isActive:         true,
        // Ferramenta
        toolType:         (item as any).toolType        ?? null,
        voltage:          (item as any).voltage         ?? null,
        power:            (item as any).power           ?? null,
        purchaseDate:     (item as any).purchaseDate    ?? null,
        warrantyMonthsTool: (item as any).warrantyMonthsTool ?? null,
        warrantyExpiry:   (item as any).warrantyExpiry  ?? null,
        isUnderWarranty:  (item as any).isUnderWarranty ?? false,
        authorizedName:   (item as any).authorizedName  ?? null,
        authorizedPhone:  (item as any).authorizedPhone ?? null,
        authorizedCity:   (item as any).authorizedCity  ?? null,
        lastMaintenance:  (item as any).lastMaintenance ?? null,
        nextMaintenance:  (item as any).nextMaintenance ?? null,
      },
    })

    console.log(`✅ ${item.code} — ${item.name}`)
    created++
  }

  console.log('\n════════════════════════════════════')
  console.log(`✅ Criados:   ${created} itens`)
  console.log(`⏭  Ignorados: ${skipped} itens`)
  console.log(`📦 Total:     ${created + skipped} itens processados`)
  console.log('════════════════════════════════════\n')
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
